# prometheus/prometheus.yml

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prometheus1

  - job_name: 'apache_exporter'
    static_configs:
      - targets: ['apache_exporter:9117']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: apache1

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: nginx1

  - job_name: 'varnish_exporter'
    static_configs:
      - targets: ['varnish_exporter:9131']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: varnish1

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: cadvisor1

  - job_name: 'stream_monitor'
    static_configs:
      - targets: ['stream-monitor:9118']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: stream_monitor1
    