{
 "title": "Streams",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "streams", "label": "Streams", "query": { "query": "label_values(stream)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Streams up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scalar(count(stream_up == 1))", "legendFormat": "__auto" },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probe score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(stream_probe_score)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Video throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(stream_video_bitrate_bps)", "legendFormat": "__auto" }
   ]
  },
  { "title": "$streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "streams" },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "stream_up{stream=\"$streams\"}"
    }
   ]
  },
  {
   "title": "Video Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "stream_video_bitrate_bps{stream=\"$streams\"}",
     "legendFormat": "{{track}}"
    }
   ]
  },
  {
   "title": "Audio Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "stream_audio_bitrate_bps{stream=\"$streams\"}",
     "legendFormat": "{{track}}"
    }
   ]
  },
  {
   "title": "Video info",
   "type": "table",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 9 },
   "targets": [
    {
     "expr": "stream_format_name{stream=\"$streams\"}"
    },
    {
     "expr": "stream_video_codec{stream=\"$streams\"}"
    },
    {
     "expr": "stream_video_track_count{stream=\"$streams\"}"
    },
    {
     "expr": "stream_video_fps{stream=\"$streams\"}"
    },
    {
     "expr": "stream_video_resolution_height_pixels{stream=\"$streams\"}"
    },
    {
     "expr": "stream_video_resolution_width_pixels{stream=\"$streams\"}"
    }
   ]
  }
 ]
}